let body = JSON.parse($response.body)
delete body.code
delete body.msg
delete body.pagecount
delete body.limit
delete body.vod_id
delete body.type_id
delete body.type_id_1
delete body.group_id
delete body.vod_sub
delete body.vod_en
delete body.vod_status
delete body.vod_letter
delete body.vod_color
delete body.vod_tag
delete body.vod_class
delete body.vod_pic_thumb
delete body.vod_pic_slide
delete body.vod_pic_screenshot
delete body.vod_pic_slide
delete body.vod_actor
delete body.vod_director
delete body.vod_writer
delete body.vod_behind
delete body.vod_blurb
delete body.vod_remarks
delete body.vod_pubdate
delete body.vod_total
delete body.vod_serial
delete body.vod_tv
delete body.vod_weekday
delete body.vod_area
delete body.vod_lang
delete body.vod_year
delete body.vod_version
delete body.vod_state
delete body.vod_author
delete body.vod_jumpurl
delete body.vod_tpl
delete body.vod_tpl_play
delete body.vod_tpl_down
delete body.vod_isend
delete body.vod_lock
delete body.vod_level
delete body.vod_copyright
delete body.vod_points
delete body.vod_points_play
delete body.vod_points_down
delete body.vod_hits
delete body.vod_hits_day
delete body.vod_hits_week
delete body.vod_hits_month
delete body.vod_duration
delete body.vod_up
delete body.vod_down
delete body.vod_score
delete body.vod_score_all
delete body.vod_score_num
delete body.vod_time
delete body.vod_time_add
delete body.vod_time_hits
delete body.vod_time_make
delete body.vod_trysee
delete body.vod_douban_id
delete body.vod_reurl
delete body.vod_douban_score
delete body.vod_rel_vod
delete body.vod_rel_art
delete body.vod_pwd
delete body.vod_pwd_url
delete body.vod_pwd_play
delete body.vod_pwd_play_url
delete body.vod_pwd_down
delete body.vod_pwd_down_url
delete body.vod_content
delete body.vod_play_from
delete body.vod_play_server
delete body.vod_play_note
$done({body: JSON.stringify(body)});                                                                　　
